### ISSUE TITLE
This Addon Will Need Updates to Work with 2021.1

### ISSUE THREAD

**Issue by fastfinge** [masonasons/Unspoken#1]
The following change breaks this addon:
https://github.com/nvaccess/nvda/pull/11969
("Module level REASON_* constants are removed from controlTypes - please use controlTypes.OutputReason instead.")

Loading it in latest snapshots, of course, results in: 
    def _hook_getSpeechTextForProperties(self, reason=NVDAObjects.controlTypes.REASON_QUERY, *args, **kwargs):
AttributeError: module 'controlTypes' has no attribute 'REASON_QUERY'

This also effects audio themes.
